import { ASSETS } from "./assets";
import type {
  Experience,
  Profile,
  Project,
  SkillGroup,
} from "./types";

export const seedProfile: Profile = {
  id: "seed-profile",
  name: "Adhitama Wichaksono",
  title: "Data Analyst & Backend Developer",
  bio: "Bachelor of Informatics graduate from Telkom University with a strong interest in Data Analytics, Machine Learning, Web Development, and Backend Development. Skilled in Python, PHP, Golang, and data visualization with Power BI.",
  location: "Jakarta, Indonesia",
  email: "adhit1312@gmail.com",
  phone: "+62 812-9058-6078",
  linkedin_url: "https://linkedin.com/in/adhitama-wichaksono-15b56b199",
  github_url: "https://github.com/adhitamaw",
  cv_url: ASSETS.cv,
  avatar_url: ASSETS.profile,
};

export const seedExperiences: Experience[] = [
  {
    id: "exp-1",
    category: "work",
    title: "Software Engineer (Internship)",
    organization: "PT. Multi Utama Consultindo (MUC Consulting)",
    location: "Jakarta, Indonesia",
    period_start: "May 2026",
    period_end: "Present",
    description: null,
    highlights: [
      "Developed a Web App GIR Reporting System to automate OECD Pillar Two GloBE Information Return XML generation for multinational clients by implementing validation rules aligned with the OECD GIR XML Schema",
      "Designed a normalized 3NF database with a centralized REST API architecture for tax reporting workflows",
    ],
    sort_order: 1,
  },
  {
    id: "exp-2",
    category: "work",
    title: "Data Analyst Fleet Management (Internship)",
    organization: "PT. Toyota-Astra Motor",
    location: "Jakarta, Indonesia",
    period_start: "October 2025",
    period_end: "December 2025",
    description: null,
    highlights: [
      "Developed and maintained Sales & Aftersales dashboards using Power BI to monitor fleet sales performance, sales trends, and operational KPIs",
      "Optimized dashboard performance by reducing loading time from ~45 seconds to 10 seconds through data model improvements, removal of unnecessary calculated columns, and DAX optimization",
      "Designed and implemented a Python-based data cleaning pipeline to automate preprocessing and improve data accuracy and consistency across multiple sources",
      "Performed regular data updates to ensure data quality and support ongoing operational and business analysis activities",
    ],
    sort_order: 2,
  },
  {
    id: "exp-3",
    category: "work",
    title: "Backend Developer (Internship)",
    organization: "Badan Pengusahaan Batam (BP Batam)",
    location: "Batam, Indonesia",
    period_start: "June 2024",
    period_end: "August 2024",
    description: null,
    highlights: [
      "Developed RESTful APIs using PHP to support data management for the SPPD Mobile system (Surat Perintah Perjalanan Dinas)",
      "Designed the SPPD Mobile database using MySQL with integrated relational tables to store application data",
      "Implemented API security via parameterized queries to prevent SQL injection, CORS configuration, and structured JSON response standards",
    ],
    sort_order: 3,
  },
  {
    id: "exp-4",
    category: "work",
    title: "AI Integration In Backend Application Development (Independent Study Program)",
    organization: "Ruangguru, Kampus Merdeka (MSIB 6)",
    location: "Remote",
    period_start: "February 2024",
    period_end: "June 2024",
    description: null,
    highlights: [
      "Developed RESTful backend services using Golang, applying clean architecture principles, middleware, and error handling",
      "Designed and optimized a PostgreSQL database through normalization, indexing, and query optimization (JOINs), integrated via ORM (GORM) for efficient data management",
      "Implemented JWT-based authentication and authorization to secure application endpoints",
    ],
    sort_order: 4,
  },
  {
    id: "exp-edu",
    category: "education",
    title: "Bachelor of Informatics",
    organization: "Telkom University, Bandung",
    location: "Bandung, Indonesia",
    period_start: "2021",
    period_end: "2025",
    description: "GPA: 3.34/4.00",
    highlights: [
      "Data Visualization",
      "Backend Engineering",
      "Database Systems",
      "Machine Learning",
      "Software Engineering",
      "Cyber Security",
      "Computer Networks",
    ],
    sort_order: 1,
  },
  {
    id: "exp-lead-1",
    category: "leadership",
    title: "Logistics Division Staff",
    organization: "Carnival HIMAIF (Informatics, Telkom University)",
    location: "Telkom University",
    period_start: "October 2023",
    period_end: "November 2023",
    description: null,
    highlights: [
      "Managed venue permits and assisted in coordinating logistics operations (procurement, vendor management, and event supply distribution)",
      "Collaborated with multiple divisions and external parties to ensure events ran on time and within budget",
    ],
    sort_order: 1,
  },
  {
    id: "exp-lead-2",
    category: "leadership",
    title: "Logistics Division Staff",
    organization: "Batavia On Telkom (Cultural Festival)",
    location: "Telkom University",
    period_start: "October 2022",
    period_end: "June 2023",
    description: null,
    highlights: [
      "Handled venue permits and vendor coordination to support event execution",
      "Managed procurement and logistics needs to ensure smooth multi-day event operations",
    ],
    sort_order: 2,
  },
  {
    id: "exp-cert-1",
    category: "certification",
    title: "Becoming Data Engineer : Teori, Praktek dan Mini Project",
    organization: "Dunia Coding",
    location: null,
    period_start: "2026",
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 1,
  },
  {
    id: "exp-cert-2",
    category: "certification",
    title: "Data Analytics and Visualization Bootcamp",
    organization: "Dsarea",
    location: null,
    period_start: "2026",
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 2,
  },
  {
    id: "exp-cert-3",
    category: "certification",
    title: "Introduction to Data Analytics",
    organization: "RevoU Mini Course",
    location: null,
    period_start: "2026",
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 3,
  },
  {
    id: "exp-cert-4",
    category: "certification",
    title: "IEEE 9th International Conference on Software Engineering & Computer Systems (ICSECS) - Published Author",
    organization: "IEEE ICSECS",
    location: null,
    period_start: "2025",
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 4,
  },
  {
    id: "exp-cert-5",
    category: "certification",
    title: "Laravel 11 Web Developer Bootcamp",
    organization: "Sanbercode",
    location: null,
    period_start: "2025",
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 5,
  },
  {
    id: "exp-cert-6",
    category: "certification",
    title: "Kampus Merdeka MSIB Batch 6 - AI Integration in Backend Application Development",
    organization: "Ruangguru",
    location: null,
    period_start: "2024",
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 6,
  },
  {
    id: "exp-pub-1",
    category: "publication",
    title: "Network Anomaly Detection for Intrusion Detection Systems Using Q-Learning and Deep Q-Learning",
    organization: "IEEE ICSECS Conference",
    location: null,
    period_start: "2025",
    period_end: null,
    description:
      "Research evaluating Q-Learning and Deep Q-Learning (DQN) for adaptive network anomaly detection using the UNSW-NB15 dataset. DQN achieved 99.09% accuracy and 0.9918 F1-score.",
    highlights: [],
    sort_order: 1,
  },
];

export const seedSkillGroups: SkillGroup[] = [
  {
    id: "sg-1",
    name: "Tools & Programming",
    icon: "code",
    sort_order: 1,
    skills: [
      { id: "s-1", group_id: "sg-1", name: "Python", sort_order: 1 },
      { id: "s-2", group_id: "sg-1", name: "SQL", sort_order: 2 },
      { id: "s-3", group_id: "sg-1", name: "Golang", sort_order: 3 },
      { id: "s-4", group_id: "sg-1", name: "PHP", sort_order: 4 },
    ],
  },
  {
    id: "sg-2",
    name: "Data & Analytics",
    icon: "analytics",
    sort_order: 2,
    skills: [
      { id: "s-5", group_id: "sg-2", name: "Exploratory Data Analysis (EDA)", sort_order: 1 },
      { id: "s-6", group_id: "sg-2", name: "Data Cleaning", sort_order: 2 },
      { id: "s-7", group_id: "sg-2", name: "Data Preprocessing", sort_order: 3 },
      { id: "s-8", group_id: "sg-2", name: "Predictive Analytics", sort_order: 4 },
      { id: "s-9", group_id: "sg-2", name: "Reporting", sort_order: 5 },
      { id: "s-10", group_id: "sg-2", name: "Excel", sort_order: 6 },
    ],
  },
  {
    id: "sg-3",
    name: "Data Visualization",
    icon: "chart",
    sort_order: 3,
    skills: [
      { id: "s-11", group_id: "sg-3", name: "Power BI", sort_order: 1 },
      { id: "s-12", group_id: "sg-3", name: "Dashboard Development", sort_order: 2 },
      { id: "s-13", group_id: "sg-3", name: "Data Storytelling", sort_order: 3 },
    ],
  },
  {
    id: "sg-4",
    name: "Database",
    icon: "database",
    sort_order: 4,
    skills: [
      { id: "s-14", group_id: "sg-4", name: "MySQL", sort_order: 1 },
      { id: "s-15", group_id: "sg-4", name: "PostgreSQL", sort_order: 2 },
    ],
  },
  {
    id: "sg-5",
    name: "Data Engineering",
    icon: "pipeline",
    sort_order: 5,
    skills: [
      { id: "s-16", group_id: "sg-5", name: "Data Pipeline Development", sort_order: 1 },
      { id: "s-17", group_id: "sg-5", name: "ETL", sort_order: 2 },
      { id: "s-18", group_id: "sg-5", name: "Data Scraping", sort_order: 3 },
      { id: "s-19", group_id: "sg-5", name: "REST API Integration", sort_order: 4 },
    ],
  },
  {
    id: "sg-6",
    name: "Web & Backend",
    icon: "api",
    sort_order: 6,
    skills: [
      { id: "s-20", group_id: "sg-6", name: "Laravel", sort_order: 1 },
      { id: "s-21", group_id: "sg-6", name: "Golang", sort_order: 2 },
    ],
  },
  {
    id: "sg-7",
    name: "Development Tools",
    icon: "tools",
    sort_order: 7,
    skills: [
      { id: "s-22", group_id: "sg-7", name: "Visual Studio Code", sort_order: 1 },
      { id: "s-23", group_id: "sg-7", name: "GitHub", sort_order: 2 },
    ],
  },
  {
    id: "sg-8",
    name: "Languages",
    icon: "languages",
    sort_order: 8,
    skills: [
      { id: "s-24", group_id: "sg-8", name: "English", sort_order: 1 },
      { id: "s-25", group_id: "sg-8", name: "Indonesia", sort_order: 2 },
    ],
  },
];

export const seedProjects: Project[] = [
  {
    id: "proj-1",
    title: "Fleet Sales Dashboard Power BI",
    subtitle: "Toyota Astra Motor Internship Project | Power BI",
    description:
      "Built a comprehensive dashboard to monitor Toyota Fleet sales performance, providing visualizations of sales target achievement, period-over-period comparisons, and in-depth analysis by customer segment and vehicle model.",
    tags: ["Microsoft Power BI", "Data Analytics", "Data Visualization"],
    year: "2025",
    project_url: null,
    doc_url: ASSETS.docs.fleet,
    image_url: ASSETS.thumbs.fleet,
    featured: true,
    sort_order: 1,
  },
  {
    id: "proj-2",
    title: "Car Sales Performance Dashboard",
    subtitle: "Data Analytics & Visualization Project | Power BI",
    description:
      "Built comprehensive Power BI dashboard tracking total sales, revenue, customer metrics, and trend analysis. Implemented dynamic filters and drill-down capabilities for granular performance insights across regions and time periods.",
    tags: ["Microsoft Power BI", "Python", "Microsoft Excel", "Critical Thinking"],
    year: "2026",
    project_url: null,
    doc_url: ASSETS.docs.car,
    image_url: ASSETS.thumbs.car,
    featured: true,
    sort_order: 2,
  },
  {
    id: "proj-3",
    title: "Bakery Sales Data Analysis",
    subtitle: "RevoU Mini Course Project – Intro to Data Analytics | Excel",
    description:
      "Analyzed bakery transaction data for January 2021 to identify peak sales periods and best-selling products. Provided data-driven recommendations to optimize weekend production and improve inventory management.",
    tags: ["Data Analytics", "Data Analysis", "Data Visualization", "Microsoft Excel", "Spreadsheets"],
    year: "2026",
    project_url: null,
    doc_url: ASSETS.docs.bakery,
    image_url: ASSETS.thumbs.bakery,
    featured: true,
    sort_order: 3,
  },
  {
    id: "proj-4",
    title: "Network Anomaly Detection for Intrusion Detection Systems",
    subtitle: "IEEE ICSECS Conference",
    description:
      "Research evaluating Q-Learning and Deep Q-Learning (DQN) for adaptive network anomaly detection using the UNSW-NB15 dataset. DQN achieved 99.09% accuracy and 0.9918 F1-score.",
    tags: ["Python", "Machine Learning", "Deep Q-Learning", "SMOTE-Tomek"],
    year: "2025",
    project_url: "https://github.com/adhitamaw/Anomaly-Detection-using-Reinforcement-Learning",
    doc_url: ASSETS.docs.ieee,
    image_url: ASSETS.thumbs.conf,
    featured: true,
    sort_order: 4,
  },
  {
    id: "proj-5",
    title: "SPPD Mobile – BP Batam",
    subtitle: "BP Batam Internship Project",
    description:
      "A Flutter-based mobile travel order management system integrated with a PHP backend and MySQL database, designed to streamline business trip administration.",
    tags: ["Flutter", "PHP", "MySQL", "REST API"],
    year: "2024",
    project_url: "https://github.com/adhitamaw/sppd",
    doc_url: null,
    image_url: null,
    featured: false,
    sort_order: 5,
  },
  {
    id: "proj-6",
    title: "Task Tracker Plus",
    subtitle: "MSIB 6 Ruangguru Project",
    description:
      "Web-based task management application built using Go (Golang). Implements Monolithic Architecture using RESTful API and follows the MVC design pattern.",
    tags: ["Go (Golang)", "REST API", "MVC", "PostgreSQL"],
    year: "2024",
    project_url: "https://github.com/adhitamaw/task-tracker-plus-go",
    doc_url: null,
    image_url: null,
    featured: false,
    sort_order: 6,
  },
  {
    id: "proj-7",
    title: "AI Model App: Translate & Chat",
    subtitle: "MSIB 6 Ruangguru Project",
    description:
      "Web-based application built with Go that integrates various AI models from Hugging Face for translation, chat/question-answering, and text processing. Features JWT-authenticated endpoints and clean architecture backend.",
    tags: ["Go (Golang)", "HuggingFace API", "JWT", "REST API"],
    year: "2024",
    project_url: "https://github.com/adhitamaw/ai-model-app-using-golang",
    doc_url: null,
    image_url: null,
    featured: false,
    sort_order: 7,
  },
];
